In [22]:
import numpy as np
import torch
x=torch.rand([1,100],dtype=torch.float32)
t=torch.linspace(0,1,11,dtype=torch.float32)
t=t.repeat(4,1)
dtype = torch.float32   
rand_move=torch.empty((4,11),dtype=dtype).uniform_(-0.05,0.05)
rand_move[:,0]=0
rand_move[:,-1]=0
t=t+rand_move

sort_t=t.sort(dim=-1)[0]
print(sort_t)
print(t)
print(sort_t==t)


tensor([[0.0000, 0.1300, 0.1792, 0.3469, 0.3984, 0.5090, 0.5838, 0.7180, 0.8414,
         0.9028, 1.0000],
        [0.0000, 0.0716, 0.2190, 0.3254, 0.4198, 0.4583, 0.6217, 0.6850, 0.7815,
         0.8932, 1.0000],
        [0.0000, 0.0986, 0.1899, 0.3465, 0.4056, 0.5473, 0.6071, 0.7126, 0.7700,
         0.9351, 1.0000],
        [0.0000, 0.1368, 0.2253, 0.2905, 0.4465, 0.4668, 0.6440, 0.7323, 0.8314,
         0.8728, 1.0000]])
tensor([[0.0000, 0.1300, 0.1792, 0.3469, 0.3984, 0.5090, 0.5838, 0.7180, 0.8414,
         0.9028, 1.0000],
        [0.0000, 0.0716, 0.2190, 0.3254, 0.4198, 0.4583, 0.6217, 0.6850, 0.7815,
         0.8932, 1.0000],
        [0.0000, 0.0986, 0.1899, 0.3465, 0.4056, 0.5473, 0.6071, 0.7126, 0.7700,
         0.9351, 1.0000],
        [0.0000, 0.1368, 0.2253, 0.2905, 0.4465, 0.4668, 0.6440, 0.7323, 0.8314,
         0.8728, 1.0000]])
tensor([[True, True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, Tru

In [32]:
import torch

def insert_points(x):
    x = torch.tensor(x, dtype=torch.float32)
    # 计算每两个点之间的中点
    mid_points = (x[:-1] + x[1:]) / 2
    # 将原始点和中点交替合并
    result = torch.empty((x.size(0) + mid_points.size(0),), dtype=x.dtype)
    result[0::2] = x
    result[1::2] = mid_points
    x=result
    return x

# 示例
x = [1, 2, 3, 4]
new_x = insert_points(x)
print(new_x)
print(new_x.shape)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000])
torch.Size([7])


AttributeError: 'NoneType' object has no attribute 'dtype'