In [1]:
import numpy as np
import torch
x=torch.rand([1,100],dtype=torch.float32)
t=torch.linspace(0,1,11,dtype=torch.float32)
t=t.repeat(4,1)
dtype = torch.float32   
rand_move=torch.empty((4,11),dtype=dtype).uniform_(-0.05,0.05)
rand_move[:,0]=0
rand_move[:,-1]=0
t=t+rand_move

sort_t=t.sort(dim=-1)[0]
print(sort_t)
print(t)



tensor([[0.0000, 0.0741, 0.1935, 0.2655, 0.3734, 0.4847, 0.6219, 0.6932, 0.8402,
         0.9096, 1.0000],
        [0.0000, 0.1017, 0.1878, 0.2769, 0.4252, 0.4978, 0.5909, 0.7338, 0.8067,
         0.8837, 1.0000],
        [0.0000, 0.1014, 0.2222, 0.3091, 0.3985, 0.5262, 0.5783, 0.6748, 0.7740,
         0.8637, 1.0000],
        [0.0000, 0.0759, 0.1652, 0.3003, 0.3541, 0.4729, 0.6257, 0.7127, 0.8289,
         0.9342, 1.0000]])
tensor([[0.0000, 0.0741, 0.1935, 0.2655, 0.3734, 0.4847, 0.6219, 0.6932, 0.8402,
         0.9096, 1.0000],
        [0.0000, 0.1017, 0.1878, 0.2769, 0.4252, 0.4978, 0.5909, 0.7338, 0.8067,
         0.8837, 1.0000],
        [0.0000, 0.1014, 0.2222, 0.3091, 0.3985, 0.5262, 0.5783, 0.6748, 0.7740,
         0.8637, 1.0000],
        [0.0000, 0.0759, 0.1652, 0.3003, 0.3541, 0.4729, 0.6257, 0.7127, 0.8289,
         0.9342, 1.0000]])


In [32]:
import torch

def insert_points(x):
    x = torch.tensor(x, dtype=torch.float32)
    # 计算每两个点之间的中点
    mid_points = (x[:-1] + x[1:]) / 2
    # 将原始点和中点交替合并
    result = torch.empty((x.size(0) + mid_points.size(0),), dtype=x.dtype)
    result[0::2] = x
    result[1::2] = mid_points
    x=result
    return x

# 示例
x = [1, 2, 3, 4]
new_x = insert_points(x)
print(new_x)
print(new_x.shape)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000])
torch.Size([7])


AttributeError: 'NoneType' object has no attribute 'dtype'

In [14]:
import numpy as np
seg_step=16
log_step=np.log2(seg_step)
#log_step=int(log_step)

print(log_step)


4.0


In [17]:
4.5//2

2.0