In [1]:
import numpy as np
import torch
x=torch.rand([1,100],dtype=torch.float32)
t=torch.linspace(0,1,11,dtype=torch.float32)
t=t.repeat(4,1)
dtype = torch.float32   
rand_move=torch.empty((4,11),dtype=dtype).uniform_(-0.05,0.05)
rand_move[:,0]=0
rand_move[:,-1]=0
t=t+rand_move

sort_t=t.sort(dim=-1)[0]
print(sort_t)
print(t)



tensor([[0.0000, 0.0741, 0.1935, 0.2655, 0.3734, 0.4847, 0.6219, 0.6932, 0.8402,
         0.9096, 1.0000],
        [0.0000, 0.1017, 0.1878, 0.2769, 0.4252, 0.4978, 0.5909, 0.7338, 0.8067,
         0.8837, 1.0000],
        [0.0000, 0.1014, 0.2222, 0.3091, 0.3985, 0.5262, 0.5783, 0.6748, 0.7740,
         0.8637, 1.0000],
        [0.0000, 0.0759, 0.1652, 0.3003, 0.3541, 0.4729, 0.6257, 0.7127, 0.8289,
         0.9342, 1.0000]])
tensor([[0.0000, 0.0741, 0.1935, 0.2655, 0.3734, 0.4847, 0.6219, 0.6932, 0.8402,
         0.9096, 1.0000],
        [0.0000, 0.1017, 0.1878, 0.2769, 0.4252, 0.4978, 0.5909, 0.7338, 0.8067,
         0.8837, 1.0000],
        [0.0000, 0.1014, 0.2222, 0.3091, 0.3985, 0.5262, 0.5783, 0.6748, 0.7740,
         0.8637, 1.0000],
        [0.0000, 0.0759, 0.1652, 0.3003, 0.3541, 0.4729, 0.6257, 0.7127, 0.8289,
         0.9342, 1.0000]])


In [32]:
import torch

def insert_points(x):
    x = torch.tensor(x, dtype=torch.float32)
    # 计算每两个点之间的中点
    mid_points = (x[:-1] + x[1:]) / 2
    # 将原始点和中点交替合并
    result = torch.empty((x.size(0) + mid_points.size(0),), dtype=x.dtype)
    result[0::2] = x
    result[1::2] = mid_points
    x=result
    return x

# 示例
x = [1, 2, 3, 4]
new_x = insert_points(x)
print(new_x)
print(new_x.shape)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000])
torch.Size([7])


AttributeError: 'NoneType' object has no attribute 'dtype'

In [14]:
import numpy as np
seg_step=16
log_step=np.log2(seg_step)
#log_step=int(log_step)

print(log_step)


4.0


In [17]:
4.5//2

2.0

In [2]:
import torch 
f=torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float32)
k=torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float32)
p=f**3/k
print(p)

tensor([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])


In [ ]:
k=torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float32)
s=k
del k
print(s)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


NameError: name 'k' is not defined

In [5]:
import numpy as np
nodes=[1,2,3,4,5,6,7,8,9,10]
sigma=0.1
sampled_points = np.array([np.random.rand()*0.1+node-0.05 for node in nodes])
print(sampled_points)

print(np.random.rand(10))

[ 1.03047958  1.95154478  3.00667492  3.98401457  5.00097549  6.02812501
  7.02654382  7.98198427  9.00194456 10.04931271]
[0.64305427 0.76273626 0.42122592 0.04155432 0.49136601 0.99445615
 0.43151844 0.99091979 0.27384835 0.79561559]
