In [2]:
import numpy as np
import torch
x=torch.rand([1,100],dtype=torch.float32)
t=torch.linspace(0,1,11,dtype=torch.float32)
t=t.repeat(4,1)
dtype = torch.float32   
rand_move=torch.empty((4,11),dtype=dtype).uniform_(-0.05,0.05)
rand_move[:,0]=0
rand_move[:,-1]=0
t=t+rand_move

sort_t=t.sort(dim=-1)[0]
print(sort_t)
print(t)



tensor([[0.0000, 0.1004, 0.1867, 0.2754, 0.3599, 0.5087, 0.6180, 0.7438, 0.8186,
         0.8992, 1.0000],
        [0.0000, 0.0849, 0.1505, 0.2630, 0.4008, 0.4763, 0.5892, 0.7295, 0.8152,
         0.9000, 1.0000],
        [0.0000, 0.1303, 0.1914, 0.3369, 0.4402, 0.4884, 0.6123, 0.6539, 0.8061,
         0.9360, 1.0000],
        [0.0000, 0.1032, 0.1731, 0.3321, 0.4212, 0.4534, 0.6303, 0.6734, 0.8015,
         0.8920, 1.0000]])
tensor([[0.0000, 0.1004, 0.1867, 0.2754, 0.3599, 0.5087, 0.6180, 0.7438, 0.8186,
         0.8992, 1.0000],
        [0.0000, 0.0849, 0.1505, 0.2630, 0.4008, 0.4763, 0.5892, 0.7295, 0.8152,
         0.9000, 1.0000],
        [0.0000, 0.1303, 0.1914, 0.3369, 0.4402, 0.4884, 0.6123, 0.6539, 0.8061,
         0.9360, 1.0000],
        [0.0000, 0.1032, 0.1731, 0.3321, 0.4212, 0.4534, 0.6303, 0.6734, 0.8015,
         0.8920, 1.0000]])


In [3]:
import torch

def insert_points(x):
    x = torch.tensor(x, dtype=torch.float32)
    # 计算每两个点之间的中点
    mid_points = (x[:-1] + x[1:]) / 2
    # 将原始点和中点交替合并
    result = torch.empty((x.size(0) + mid_points.size(0),), dtype=x.dtype)
    result[0::2] = x
    result[1::2] = mid_points
    x=result
    return x

# 示例
x = [1, 2, 3, 4]
new_x = insert_points(x)
print(new_x)
print(new_x.shape)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000])
torch.Size([7])


In [4]:
import numpy as np
seg_step=16
log_step=np.log2(seg_step)
#log_step=int(log_step)

print(log_step)


4.0


In [5]:
4.5//2

2.0

In [4]:
import torch 
f=torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float32)
k=torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float32)
p=f**3/k
print(p)
k=torch.tensor([0.50000006],dtype=torch.float32)

print('showing float32 precision:\n','example: for num 0.50000006') 
print('in float32:',k.item())



tensor([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])
showing float32 precision:
 example: for num 0.50000006
in float32: 0.5000000596046448


In [7]:
k=torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float32)
s=k
del k
print(s)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [8]:
import numpy as np
nodes=[1,2,3,4,5,6,7,8,9,10]
sigma=0.1
sampled_points = np.array([np.random.rand()*0.1+node-0.05 for node in nodes])
print(sampled_points)

print(np.random.rand(10))

[ 1.0184515   2.01751547  2.96465458  4.04186892  5.00287753  6.02943719
  6.97912415  7.95339939  9.04786839 10.04804576]
[0.44284439 0.73449773 0.57816676 0.12256346 0.01729761 0.761441
 0.70595094 0.1053051  0.27286948 0.23242353]


In [14]:
sampled_points=np.array([1,2,3,4,5,6,7,8,9,10])
print(sampled_points.size)
temp_result=np.zeros((sampled_points.size))
print(temp_result)

10
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
with open('draft.txt', 'a+') as f:
    f.write('Hello\n')
    f.write('World\n')